### ISSUE TITLE
[BUG] After updating to v2.7.1 pwnagotchi constantly crashing

### ISSUE THREAD

**Issue by wizardofyendor** [jayofelony/pwnagotchi-bookworm#14]
**Describe the bug**
After updating to v2.7.1 pwnagotchi constantly crashing.  The log isn't updated with the failures, but when run it with debug I get:  [pwnagotchi --debug.txt](https://github.com/jayofelony/pwnagotchi-bookworm/files/13970028/pwnagotchi.--debug.txt)

[2024-01-17 23:55:26,284] [INFO] error 400: error while initializing wlan0mon to channel 1: iw: out=command failed: Device or resource busy (-16) err=exit status 240
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/pwnagotchi/bettercap.py", line 24, in decode
    return r.json()
           ^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pwnagotchi", line 230, in <module>
    pwnagotchi_cli()
  File "/usr/local/bin/pwnagotchi", line 226, in pwnagotchi_cli
    do_auto_mode(agent)
  File "/usr/local/bin/pwnagotchi", line 52, in do_auto_mode
    agent.start()
  File "/usr/local/lib/python3.11/dist-packages/pwnagotchi/agent.py", line 136, in start
    self.start_monitor_mode()
  File "/usr/local/lib/python3.11/dist-packages/pwnagotchi/agent.py", line 118, in start_monitor_mode
    self.start_module('wifi.recon')
  File "/usr/local/lib/python3.11/dist-packages/pwnagotchi/agent.py", line 404, in start_module
    self.run('%s on' % module)
  File "/usr/local/lib/python3.11/dist-packages/pwnagotchi/bettercap.py", line 119, in run
    return decode(r, verbose_errors=verbose_errors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pwnagotchi/bettercap.py", line 32, in decode
    raise Exception(err)
Exception: error 400: error while initializing wlan0mon to channel 1: iw: out=command failed: Device or resource busy (-16) err=exit status 240

**To Reproduce**
Just booting my device / service causes these failures.

**Environment (please complete the following information):**
 - Pwnagotchi version: 2.7.1
 - OS version: bookworm
 - Type of hardware: rpi4
 - Any additional hardware used: waveshare_v4

**Additional context**

I'm unable to update to 2.7.2 using pwnagotchi --check-update as it doesn't stay running long enough to update.

I've commented out all plugins in my config.toml to no avail.  

[pwnagotchi.log](https://github.com/jayofelony/pwnagotchi-bookworm/files/13969900/pwnagotchi.log)
[config.toml.txt](https://github.com/jayofelony/pwnagotchi-bookworm/files/13969901/config.toml.txt)

**Comment by jayofelony** [comment]
Yes, get into manual mode itll update 2.7.2 and be fixed.
