### ISSUE TITLE
[BUG] Plugins List Broken

### ISSUE THREAD

**Issue by hamzenis** [jayofelony/pwnagotchi-bookworm#63]
**Describe the bug**
When calling Pwnagotchi cli with list a python error occurs 

``` bash
pi@Nisi:~ $ sudo pwnagotchi plugins list
Traceback (most recent call last):
  File "/usr/local/bin/pwnagotchi", line 235, in <module>
    pwnagotchi_cli()
  File "/usr/local/bin/pwnagotchi", line 152, in pwnagotchi_cli
    rc = plugins_cmd.handle_cmd(args, config)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pwnagotchi/plugins/cmd.py", line 85, in handle_cmd
    return list_plugins(args, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pwnagotchi/plugins/cmd.py", line 202, in list_plugins
    max_len = max(map(len, max_len_list))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: max() arg is an empty sequence
```
**To Reproduce**
1. Call `sudo pwnagotchi plugins list`

**Expected behavior**
List of available plugins

**Screenshots**
<img width="1406" alt="Screenshot 2024-02-15 at 00 12 38" src="https://github.com/jayofelony/pwnagotchi-bookworm/assets/84898985/6fd23886-0b31-4950-b219-165893807a94">

**Environment (please complete the following information):**
 - Pwnagotchi version 2.8.3
 - OS version Debian GNU/Linux 12 (bookworm)
 - Type of hardware RP2W
 - Any additional hardware used Waveshare v4

**Additional context**
Fresh Install from today. Just got new board

**Comment by hamzenis** [comment]
Oh my bad. Sorry for the inconvenience
